[project]
name = "shruti"
version = "0.1.3"
description = "Indic Conformer ASR Lib"
readme = "README.md"
authors = [
    { name = "dummyjenil", email = "dummyjenil@gmail.com" }
]
dependencies = [
    'librosa',
    'numpy',
    'torchcodec',
    'torch',
    'torchaudio',
    'tqdm',
    'huggingface_hub',
    'webrtcvad',
    'srt',
    'safetensors',
    'transformers',
    'torch_state_bridge',
]

[project.optional-dependencies]
nemo = [
 'transformers',
 'torchcodec',
 'onnx',
 'ruamel.yaml',
 'text-unidecode',
 'wget',
 'braceexpand',
 'editdistance',
 'g2p_en',
 'jiwer',
 'kaldi-python-io',
 'kaldiio',
 'lhotse',
 'pyannote.core',
 'pyannote.metrics',
 'pyloudnorm',
 'resampy',
 'ruamel.yaml',
 'sox',
 'numba',
 'python-dateutil',
 'scikit-learn',
 'setuptools',
 'tensorboard',
 'wrapt',
 'ipywidgets',
 'marshmallow',
 'matplotlib',
 'packaging',
 'pydub',
 'scipy',
 'soundfile',
 'webdataset',
 'pytorch-lightning',
 'hydra-core',
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
